# Generated by Django 4.1.3 on 2022-11-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('localizacion', models.CharField(max_length=30)),
                ('tipoTienda', models.CharField(max_length=10)),
                ('entregaDomicilio', models.CharField(max_length=10)),
                ('horario', models.CharField(max_length=10)),
                ('comprasOnline', models.CharField(max_length=10)),
            ],
        ),
    ]
