# Generated by Django 4.1.3 on 2022-11-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_ropa', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=15)),
                ('talla', models.CharField(max_length=5)),
                ('temporada', models.CharField(max_length=20)),
                ('estilo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('tienda', models.CharField(max_length=20))
            ],
        ),
    ]
