# Generated by Django 4.1.3 on 2022-11-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ropa', '0003_alter_ropa_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='tienda',
            field=models.CharField(max_length=20),
        ),
    ]
