# Generated by Django 4.1.3 on 2022-11-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
        ('Ropa', '0004_alter_ropa_tienda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ropa',
            old_name='tipo_de_ropa',
            new_name='tipoRopa',
        ),
        migrations.AlterField(
            model_name='ropa',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.tienda'),
        ),
    ]
