# Generated by Django 4.1.3 on 2022-11-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juguetes', '0002_alter_juguetes_tienda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juguetes',
            old_name='tienda',
            new_name='tienda_id',
        ),
    ]
