# Generated by Django 4.1.3 on 2022-11-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juguetes', '0003_rename_tienda_juguetes_tienda_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juguetes',
            old_name='tienda_id',
            new_name='tienda',
        ),
    ]
